name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  IMAGE_NAME: skiloop/echo-server
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: env GO111MODULE=on GOOS=linux GOARCH=amd64 go build  -ldflags="-s -w" -v ./

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
        push: true
        tags: skiloop/echo-server:latest

